rsvpapp:
  build: .
  command: rails server -p 3000 -b '0.0.0.0'
  volumes:
    - .:/usr/src/app
  ports:
    - "3000:3000"
  links:
    - rsvpdb
  environment:
    DB_HOST: rsvpdb
    DB_PORT: 5432
    DB_USERNAME: postgres
    DB_PASSWORD:
rsvpdb:
  image: postgres:9.4
  ports:
    - "5432:5432"
